import type { MarketplaceRules } from "./types";
import { ADOBE_KEYWORDS_MAX, ADOBE_TITLE_MAX } from "@/lib/stock-spec";

const TRADEMARK_TERMS = [
  "iphone",
  "ipad",
  "macbook",
  "imac",
  "apple watch",
  "playstation",
  "xbox",
  "nintendo",
  "wii",
  "lego",
  "coca-cola",
  "pepsi",
  "mcdonald",
  "mcdonald's",
  "kfc",
  "burger king",
  "starbucks",
  "netflix",
  "spotify",
  "tiktok",
  "whatsapp",
  "instagram",
  "facebook",
  "twitter",
  "youtube",
  "google",
  "amazon",
  "ebay",
  "walmart",
  "alibaba",
  "disney",
  "pixar",
  "marvel",
  "gucci",
  "louis vuitton",
  "prada",
  "chanel",
  "dior",
  "rolex",
  "tiffany",
  "cartier",
  "nike",
  "adidas",
  "puma",
  "lamborghini",
  "ferrari",
  "porsche",
  "maserati",
  "harley-davidson",
  "tesla",
  "mercedes",
  "bmw",
  "audi",
  "volkswagen",
  "microsoft",
  "samsung",
  "xiaomi",
  "huawei",
  "toyota",
  "honda",
  "nissan",
  "ford",
  "chevrolet",
  "red bull",
  "monster energy",
  "paypal",
  "visa",
  "mastercard",
];

const CAMERA_TERMS = [
  "canon",
  "nikon",
  "sony",
  "dslr",
  "slr",
  "megapixel",
  "aperture",
  "shutter speed",
  "iso",
  "f-stop",
  "wide angle",
  "telephoto",
  "macro lens",
  "prime lens",
  "zoom lens",
  "tripod",
  "exposure",
  "white balance",
  "raw format",
  "camera settings",
  "focal length",
];

const TITLE_FILLER_TERMS = [
  "stock photo",
  "stock image",
  "stock photography",
  "high quality",
  "high resolution",
  "high-res",
  "premium",
  "professional",
  "stunning",
  "beautiful",
  "amazing",
  "perfect",
  "unique",
  "best",
  "great",
  "nice",
  "awesome",
  "royalty free",
  "royalty-free",
  "hd",
  "4k",
  "adobe stock",
  "shutterstock",
  "best seller",
  "top seller",
  "wallpaper",
];

const KEYWORD_FILLER_TERMS = [
  "stock photo",
  "stock image",
  "stock photography",
  "high quality",
  "high resolution",
  "premium",
  "professional",
  "stunning",
  "beautiful",
  "amazing",
  "perfect",
  "awesome",
  "nice",
  "best",
  "great",
  "unique",
  "royalty free",
  "free",
  "hd",
  "4k",
  "image",
  "photo",
  "picture",
  "wallpaper",
  "concept",
  "design",
  "creative",
  "abstract",
  "modern",
  "minimal",
  "minimalist",
  "simple",
  "clean",
  "bright",
  "vibrant",
  "colorful",
  "background",
  "texture",
  "pattern",
  "space",
  "copy",
  "realistic",
  "isolated",
  "view",
  "sample",
  "example",
  "template",
  "stock",
  "clipart",
  "clip art",
];

export const ADOBE_RULES: MarketplaceRules = {
  id: "adobe",
  label: "Adobe Stock",
  titleMax: ADOBE_TITLE_MAX,
  descriptionMax: 0,
  keywordMin: 1,
  keywordMax: ADOBE_KEYWORDS_MAX,
  keywordMaxWords: 2,
  titleGuidance:
    "Write a concise, factual, descriptive title up to {titleMax} characters that names the main subject first and reads as a natural phrase or sentence. It must NEVER be a comma-separated list of keywords. Do not use generic filler such as 'professional', 'high quality', 'premium', 'stunning', or 'beautiful', and do not use trademarked brand names or camera information. Good example: 'Red double-decker bus crossing London Bridge at dusk'. Bad example: 'bus, bridge, city, sunset, red, travel'.",
  descriptionGuidance:
    "Adobe Stock does not use a description field; always return an empty string for adobe.description.",
  keywordGuidance:
    "Provide the requested number of keywords. STRONGLY prefer single-word keywords — only use a two-word phrase when the single word alone would lose critical meaning. Order strictly by search importance: the strongest, most specific, high-intent terms first (primary subject, action, important objects, style, medium, colors, composition, setting, commercial concepts). Every keyword must be visually supported and correctly spelled. No duplicates or near-duplicates (case-insensitive); if both 'business' and 'business strategy' appear, keep only the stronger one. No truncated words, generic filler, trademarked brands, camera information, or filename tokens. No keyword stuffing — do not pad with weak or loosely related terms.",
  categoryGuidance:
    "Choose exactly ONE numeric Adobe Stock category ID that best matches the actual asset type and subject, and output only the number. Official categories (ID Label): {ADOBE_CATEGORIES}",
  trademarkTerms: TRADEMARK_TERMS,
  cameraTerms: CAMERA_TERMS,
  titleFillerTerms: TITLE_FILLER_TERMS,
  keywordFillerTerms: KEYWORD_FILLER_TERMS,
  titleListPattern: /[,;|]/,
  forbidBrands: true,
  forbidCameraInfo: true,
  forbidPii: true,
  forbidLinks: true,
};
