import type { MarketplaceRules } from "./types";
import {
  SHUTTERSTOCK_KEYWORDS_MAX,
  SHUTTERSTOCK_KEYWORDS_MIN,
  SHUTTERSTOCK_TITLE_MAX,
} from "@/lib/stock-spec";

const TRADEMARK_TERMS = [
  "iphone",
  "ipad",
  "macbook",
  "imac",
  "apple watch",
  "playstation",
  "xbox",
  "nintendo",
  "wii",
  "lego",
  "coca-cola",
  "pepsi",
  "mcdonald",
  "mcdonald's",
  "kfc",
  "burger king",
  "starbucks",
  "netflix",
  "spotify",
  "tiktok",
  "whatsapp",
  "instagram",
  "facebook",
  "twitter",
  "youtube",
  "google",
  "amazon",
  "ebay",
  "walmart",
  "alibaba",
  "disney",
  "pixar",
  "marvel",
  "gucci",
  "louis vuitton",
  "prada",
  "chanel",
  "dior",
  "rolex",
  "tiffany",
  "cartier",
  "nike",
  "adidas",
  "puma",
  "lamborghini",
  "ferrari",
  "porsche",
  "maserati",
  "harley-davidson",
  "tesla",
  "mercedes",
  "bmw",
  "audi",
  "volkswagen",
  "microsoft",
  "samsung",
  "xiaomi",
  "huawei",
  "toyota",
  "honda",
  "nissan",
  "ford",
  "chevrolet",
  "red bull",
  "monster energy",
  "paypal",
  "visa",
  "mastercard",
];

const CAMERA_TERMS = [
  "canon",
  "nikon",
  "sony",
  "dslr",
  "slr",
  "megapixel",
  "aperture",
  "shutter speed",
  "iso",
  "f-stop",
  "wide angle",
  "telephoto",
  "macro lens",
  "prime lens",
  "zoom lens",
  "tripod",
  "exposure",
  "white balance",
  "raw format",
  "camera settings",
  "focal length",
];

const TITLE_FILLER_TERMS = [
  "stock photo",
  "stock image",
  "stock photography",
  "high quality",
  "high resolution",
  "high-res",
  "premium",
  "professional",
  "stunning",
  "beautiful",
  "amazing",
  "perfect",
  "unique",
  "best",
  "great",
  "nice",
  "awesome",
  "royalty free",
  "royalty-free",
  "hd",
  "4k",
  "adobe stock",
  "shutterstock",
  "best seller",
  "top seller",
  "wallpaper",
];

const KEYWORD_FILLER_TERMS = [
  "stock photo",
  "stock image",
  "stock photography",
  "high quality",
  "high resolution",
  "premium",
  "professional",
  "stunning",
  "beautiful",
  "amazing",
  "perfect",
  "awesome",
  "nice",
  "best",
  "great",
  "unique",
  "royalty free",
  "free",
  "hd",
  "4k",
  "image",
  "photo",
  "picture",
  "wallpaper",
  "concept",
  "design",
  "creative",
];

export const SHUTTERSTOCK_RULES: MarketplaceRules = {
  id: "shutterstock",
  label: "Shutterstock",
  titleMax: SHUTTERSTOCK_TITLE_MAX,
  descriptionMax: SHUTTERSTOCK_TITLE_MAX,
  keywordMin: SHUTTERSTOCK_KEYWORDS_MIN,
  keywordMax: SHUTTERSTOCK_KEYWORDS_MAX,
  keywordMaxWords: 2,
  titleGuidance:
    "Write a descriptive title as a natural sentence or phrase up to {titleMax} characters that states the main subject and action. It must NEVER be a comma-separated or pipe-separated list of keywords. Do not include trademarked brand names, camera information, model numbers, phone numbers, email addresses, website URLs, or personal data, and never use generic filler such as 'professional', 'high quality', or 'premium'. Good example: 'A smiling barista pouring latte art in a cozy coffee shop'. Bad example: 'coffee, barista, latte, art, cup'.",
  descriptionGuidance:
    "Write 1-2 factual sentences (up to {descriptionMax} characters) describing the subject, setting, and action. No marketing language, no website URLs, no contact information, no camera information, and no trademarked brand names.",
  keywordGuidance:
    "Provide the requested number of keywords (7 to 50). Every keyword must be ONE word or a natural TWO-word phrase, never more. Order strictly by search importance: the strongest, most specific, high-intent terms first (primary subject, action, important objects, style, medium, colors, composition, setting, commercial concepts). Every keyword must be visually supported and correctly spelled. No duplicates, near-duplicates, truncated words, generic filler, trademarked brands, camera information, email addresses, phone numbers, website URLs, or filename tokens.",
  categoryGuidance:
    "Choose 1-2 exact official Shutterstock category names that best match the asset type and subject, and output them separated by a comma. Official categories: {SHUTTERSTOCK_CATEGORIES}",
  trademarkTerms: TRADEMARK_TERMS,
  cameraTerms: CAMERA_TERMS,
  titleFillerTerms: TITLE_FILLER_TERMS,
  keywordFillerTerms: KEYWORD_FILLER_TERMS,
  titleListPattern: /([,;])(?=[^,;]*[,;])|\|/,
  forbidBrands: true,
  forbidCameraInfo: true,
  forbidPii: true,
  forbidLinks: true,
};
